# Generated by Django 5.1.7 on 2025-03-24 03:47

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0004_certificates_projectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('job_details', ckeditor.fields.RichTextField(max_length=20000)),
                ('posted_date', models.DateField()),
                ('end_date', models.DateField()),
                ('post_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL identifier for the category', max_length=255, unique=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(default=django.utils.timezone.now, help_text='SEO-friendly description for the blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(default=django.utils.timezone.now, help_text='SEO-friendly title for the blog', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Unique URL-friendly identifier for the blog', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vynzora_app.career_model')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='website_images/')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('add_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='vynzora_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, verbose_name='Service Heading')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vynzora_app.website')),
            ],
        ),
    ]
