# Generated by Django 5.1.7 on 2025-03-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0005_career_model_category_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
