# Generated by Django 6.0.2 on 2026-03-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0007_faq_newsletter_partner_promotionalbanner_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
