# Generated by Django 6.0.2 on 2026-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0011_delete_legacyservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='services',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
