# Generated by Django 6.0.2 on 2026-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0012_alter_services_options_services_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='seo_h1_title',
            field=models.CharField(blank=True, help_text='Custom H1 heading for the service detail page hero. Leave blank to use the service Name.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='seo_h2_title',
            field=models.CharField(blank=True, help_text='Custom H2 heading for the service details section. Leave blank to use the service Name.', max_length=200, null=True),
        ),
    ]
